animations {
    enabled = yes
    bezier = smooth, 0.25, 1, 0.5, 1
    
    animation = windows, 1, 5, smooth
    animation = windowsOut, 1, 5, default, popin 80%
    animation = border, 1, 10, default
    animation = fade, 1, 5, default
    animation = workspaces, 1, 4, default, slide
}