# Browser Picture-in-Picture & Dialogs
windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = pin on, match:title ^(Picture-in-Picture)$
windowrule = move 70% 70%, match:title ^(Picture-in-Picture)$
windowrule = size 25% 25%, match:title ^(Picture-in-Picture)$

# Float browser dialogs (Open File, Save As, etc)
windowrule = float on, match:title ^(Open File|Save File|Save As|Opening.*)$

# System Utilities
windowrule = float on, match:class ^(org.pulseaudio.pavucontrol|pavucontrol)$
windowrule = size 800 500, match:class ^(org.pulseaudio.pavucontrol|pavucontrol)$
windowrule = float on, match:class ^(blueman-manager)$
windowrule = size 600 400, match:class ^(blueman-manager)$
windowrule = float on, match:class ^(nm-connection-editor)$

# Media & Image Viewers
windowrule = float on, match:class ^(org.gnome.Loupe|eog)$
windowrule = float on, match:class ^(vlc)$