exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = quickshell -d
exec-once = swww-daemon
exec-once = swaync
exec-once = ~/.config/hypr/scripts/wallpaper.sh --init

# Clipboard History
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store