source = config/programs.conf
source = config/env.conf
source = config/monitors.conf
source = config/input.conf
source = config/apperance.conf
source = config/animations.conf
source = config/keybinds.conf
source = config/rules.conf
source = config/startup.conf
source = config/fixes.conf

source = custom.conf